/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package locadoraveiculosmultimarcas;

import locadoraveiculosmultimarcas.gui.TelaPrincipal;


public class App {
    
   public static SqlUtil SqlUtil = new SqlUtil ("localhost", "5432", "luciene locadora", "postgres", "postgres");
            
    public static void main(String[] args) {
        TelaPrincipal form = new TelaPrincipal();
        form.setVisible(true);
        
    }
}
